export const clientActionTypes = {
    GET_ALL_USER: "GET_ALL_USER",
    GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
    GET_ALL_USER_ERROR: "GET_ALL_USER_ERROR",
    CREATE_USER: "CREATE_USER",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_ERROR: "CREATE_USER_ERROR",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_ERROR: "GET_USER_DETAILS_ERROR",
    DELETE_USER: "DELETE_USER",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_ERROR: "DELETE_USER_ERROR",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
    RESET: "RESET"
}